# This project config file describes your project. See looper docs for details.
name: project_name # The name that summary files will be prefaced with

pep_version: 2.0.0
sample_table: PEPATAC_annotation.csv  # sheet listing all samples in the project

looper:  # relative paths are relative to this config file
  output_dir: "/full/path/to/out/dir"  # path where the output files will be written
  pipeline_interfaces: ["$CODE/project_pipeline_interface.yaml"]  # DO NOT CHANGE!

sample_modifiers:
  append:
    pipeline_interfaces: ["$CODE/sample_pipeline_interface.yaml"] # DO NOT CHANGE!
  derive:
    attributes: [read1, read2] # which columns looper is looking at in the annotation file
    sources:
      sample1_R1: "/path/to/sample1_R1.fastq.gz"
      sample1_R2: "/path/to/sample1_R2.fastq.gz"
      sample2_R1: "/path/to/sample2_R1.fastq.gz"
      sample2_R2: "/path/to/sample2_R2.fastq.gz"
  imply:
    - if:
        organism: ["human", "Homo sapiens", "Human", "Homo_sapiens"]
      then:
        genome: hg38
        macs_genome_size: hs
        prealignments: "rCRSd human_repeats"
        deduplicator: samblaster # Default. [options: picard]
        trimmer: skewer          # Default. [options: pyadapt, trimmomatic]
        peak_type: fixed         # Default. [options: variable]
        extend: 250              # Default. For fixed-width peaks, extend this distance up- and down-stream.
        frip_ref_peaks: None     # Default. Use an external reference set of peaks instead of the peaks called from this run
        blacklist: $GENOMES/hg38/blacklist/default/hg38_blacklist.bed.gz
        motif: TRUE
        no_scale: TRUE       
    - if:
        organism: ["mouse", "Mus muculus", "Mouse", "Mus_musculus"]
      then:
        genome: mm10
        macs_genome_size: mm
        prealignments: mouse_chrM2x
        deduplicator: samblaster # Default. [options: picard]
        trimmer: skewer          # Default. [options: pyadapt, trimmomatic]
        peak_type: fixed         # Default. [options: variable]
        extend: 250              # Default. For fixed-width peaks, extend this distance up- and down-stream.
        frip_ref_peaks: None     # Default. Use an external reference set of peaks instead of the peaks called from this run
        blacklist: $GENOMES/mm10/blacklist/default/mm10_blacklist.bed.gz
        motif: TRUE
        no_scale: TRUE
